Added new configuration support, particular refactoring
datopian/ourbot pull request #14
Opened 2017-04-10 13:35 UTC by weirdGuy

Added new configuration support( #8 and #9 and #6  )
```javascript
{
    "docs": {
        "gdoc1": {
            "fun": "sendMessage" // the name of the function to call for logging
        }
    },
    "monitor": {
        "+todo": { // the command which we are monitoring
            "action": "log",  // what we should do (in developing)
            "dest": "gdoc1" // where we will save (calls "fun" from "docs" -> "gdoc1")
        },
        "+standup": {
            "action": "log",
            "dest": "gdoc1"
        }
    }
}

```

2017-04-10 14:11 UTC, zelima requested changes

2017-04-10 14:11 UTC, zelima commented on scripts/main.coffee
> +          if(key == message[0])
This means +todo should always be in the beginning of the sentence right?  we want script to handle it in the meddle or at the end as well

2017-04-10 14:16 UTC, weirdGuy commented on scripts/main.coffee
> +          if(key == message[0])
hmmm, but i think more preferrable format would be to type command in the beginning, but if you want also to fetch it in the end -- i can do this

2017-04-11 05:20 UTC, zelima approved these changes

2017-04-11 05:20 UTC, merged