Gists support, new way of loggers specification
datopian/ourbot pull request #27
Opened 2017-04-15 19:07 UTC by weirdGuy

Added support for loggin into gists(#17), also added "room" parameter to gdoc logging(#22).
Edited config according to specification #8

2017-04-15 20:38 UTC, rufuspollock commented
Looks reasonable but I don't see *any* tests so can't approve this PR. The PR **must** include tests for the new features or a detailed explanation of why tests are not possible or not needed.

Small comment re commit messages: saying "Update main.coffee" does not tell me a lot. Please have informative commit messages that tell the reader (that includes you in the future) something about what is really happening.

2017-04-15 20:42 UTC, weirdGuy commented
@rufuspollock Commit messages about "update main.coffee" was made through github and include only deletion of commented code that not needed

2017-04-16 10:39 UTC, rufuspollock commented
@weirdGuy 

> Commit messages about "update main.coffee" was made through github and include only deletion of commented code that not needed

then say that in the commit message e.g.

```
[xs]: Delete commented code from main.coffee that is not needed.
```

2017-04-16 10:40 UTC, weirdGuy commented
@rufuspollock alright, so i need to revert commits? and push them again?

2017-04-16 10:42 UTC, rufuspollock commented
@weirdGuy no, don't bother but this is important for the future.

2017-04-16 10:43 UTC, rufuspollock requested changes
See comments.

2017-04-16 10:43 UTC, rufuspollock commented on test/messages-test.js
> +        sinon.stub(messages, "sendGist", function () {
You need to stub at a deeper level than this. As it currently stands this test is pointless as it does not test anything.

You would really want to stub the method that does the call out to the github gist API if you could.

2017-04-16 10:43 UTC, rufuspollock commented on test/messages-test.js
> +        sinon.stub(messages, "sendMessage", function () {
You need to stub at a deeper level than this - as it currently stands this test is pointless (it does not test anything).

You want to stub method that does the call out to the google docs API if you could e.g. stub the doc.addRow method in the underlying method.

2017-04-16 11:10 UTC, rufuspollock commented
I'm going to merge this for now even though tests are empty so we can keep moving forward (and deploying)!

2017-04-16 11:10 UTC, merged