Feartures/help message
datopian/ourbot pull request #49
Opened 2017-08-17 19:44 UTC by Mikanebu

* added help response for command `\ourbot help` pointing to the `README.md` usage section
* added `resolver` repo into list of repos

2017-08-18 18:23 UTC, rufuspollock commented on extras/closeMilestones.js
> +  {owner: 'datahq', repo: 'resolver'},
This commit would be better as a simple push outside of this pull request (it is not part of the changes described in this PR).

But not a biggie!

2017-08-18 18:25 UTC, rufuspollock requested changes

2017-08-18 18:25 UTC, rufuspollock commented on README.md
> +In your chat channel tag at start, middle or end of a message: `+todo`, `+standup`, `+examples`
This should have a heading e.g. `## TODOs` so that it can be specifically linked to from the help

2017-08-18 18:25 UTC, rufuspollock commented on scripts/main.js
> +        res.send("Hi, I'm your helpful chatops bot! Please, see README for the usage https://github.com/datopian/ourbot#how-to-use-it")
This should list the main commands available and link them to the README as we discussed when planning this work.

2017-08-18 18:32 UTC, Mikanebu commented on scripts/main.js
> +        res.send("Hi, I'm your helpful chatops bot! Please, see README for the usage https://github.com/datopian/ourbot#how-to-use-it")
@rufuspollock Yes, it was created yesterday, i modified as you suggested. Trying to write unittest. Btw, you can check now writing `bot` or `/bot` to get a response

2017-08-20 18:08 UTC, rufuspollock commented on Procfile
> -web: HUBOT_GITTER2_TOKEN=$HUBOT_GITTER2_TOKEN bin/hubot -a gitter2 --name ourbot
This should be part of a separate commit or change - it is not part of this PR 😄

2017-08-20 18:10 UTC, rufuspollock commented on test/parsing-test.js
> +    it('starting with bot should reply help message', function () {
No, this is not correct. I would suggest it only replies with help message if the message starts with bot and only contains bot or you have bot help e.g.

```
bot
bot help
/bot
/bot help
```

Anything else should not generate a help message.

2017-08-20 18:10 UTC, rufuspollock commented on test/parsing-test.js
> +    it('starting with bot should reply help message', function () {
And great we have these tests so we can see this!

2017-08-20 18:10 UTC, rufuspollock commented on test/parsing-test.js
> +
Why do we have whitespace here ...

2017-08-20 18:10 UTC, rufuspollock commented on test/parsing-test.js
> +        return room.user.say('weirdguy', "do +todo this one").then(function () {
Why are we returning this now vs before?

2017-08-21 06:51 UTC, Mikanebu commented on test/parsing-test.js
> +    it('starting with bot should reply help message', function () {
@rufuspollock will be fixed

2017-08-21 10:35 UTC, merged